circuit:
  hilbert_dimension: 31
  max_steps: 50
  initial_sqz: -1.15
  max_sqz: 1.15
  max_disp: 0.0
  loss: 0.0
  penalty_exponent: 50.0
  reward_func: "fidelity"
  circuit_type: "cz~d-angle"
  state_type: "dm"
model:
  total_timesteps: 15_000_000
  gamma: 0.999
  num_epochs: 15
  batch_size: 5_000
  buffer_size: 35_000
  clip_range: 0.20
  learning_rate: 0.001
  use_lstm: True
  hidden_layers: [128, 128, 64]
  activation_func: "relu"
